export const GameConfig = {
    TICK_RATE: 10,
    TICK_STEP_MS: 100,
    MAP_WIDTH: 256,
    MAP_HEIGHT: 256,
    CONVEYOR_SPEED: 0.5,
    MINER_EXTRACTION_TICKS: 10,
    ASSEMBLER_CRAFT_TICKS: 20,
} as const;
